host:
  ip:
    rabbitmq: 192.168.2.101
    redis: 192.168.2.101
    nacos: 127.0.0.1
    mysql: 127.0.0.1
spring:
  #服务名称
  application:
    name: nacos-provider2
  #nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: ${host.ip.nacos}:8848
  #数据库连接池
  datasource:
    druid:
      username: root
      password: 111111
      url: jdbc:mysql://${host.ip.mysql}:3306/myshop?useUnicode=true&characterEncoding=utf8
      initial-size: 10
      max-active: 50
      validation-query: select 1
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 20
  #redis配置
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    sentinel:
      master: mymaster
      nodes: ${host.ip.redis}:26379, ${host.ip.redis}:26380, ${host.ip.redis}:26381
  #MQ
  rabbitmq:
    addresses: ${host.ip.rabbitmq}:5672
    connection-timeout: 15000
    password: guest
    username: guest
    publisher-confirms: true
    virtual-host: /
    ##以下两个配置一组
    publisher-returns: true
    template:
      mandatory: true
    #消费者配置
    listener:
      order:
        exchange:
          durable: true
          ignoreDeclarationExceptions: true
          name: exchange-2
          type: topic
        key: springboot.*
        queue:
          durable: true
          name: queue-2
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10

server:
  port: 8082

#端点检查
management:
  endpoints:
    web:
      exposure:
        include: "*"

##mybatis配置
mybatis:
  type-aliases-package: com.zlm.hello.spring.cloud.alibaba.nacos.provider2.model
  mapper-locations: classpath:mapper/*Mapper*.xml
  configuration:
    cache-enabled: true
logging:
  level:
   com.zlm.hello.spring.cloud.alibaba.nacos.provider.dao : debug